export const LAT_LNG_SELECTED = 'LAT_LNG_SELECTED';
export const LAT_LNG_LOOKUP_STARTED = 'LAT_LNG_LOOKUP_STARTED';
export const LAT_LNG_LOOKUP_FINISHED = 'LAT_LNG_LOOKUP_FINISHED';
export const DIRECTIONS_FOUND = 'DIRECTIONS_FOUND';
export const ELEVATIONS_UPDATED = 'ELEVATIONS_UPDATED';

// user controls
export const UNDO = 'UNDO';
export const RESET = 'RESET';

// highlights
export const HIGHLIGHT_SELECTED = 'HIGHLIGHT_SELECTED';
export const HIGHLIGHT_CLOSED = 'HIGHLIGHT_CLOSED';
export const HIGHLIGHT_ADDED = 'HIGHLIGHT_ADDED';
