export const LAT_LNG_SELECTED = 'LAT_LNG_SELECTED';
export const LAT_LNG_LOOKUP_STARTED = 'LAT_LNG_LOOKUP_STARTED';
export const LAT_LNG_LOOKUP_FINISHED = 'LAT_LNG_LOOKUP_FINISHED';
export const DIRECTIONS_FOUND = 'DIRECTIONS_FOUND';

// user controls
export const UNDO = 'UNDO';
